version: '3'
services:

  eth-node:
    image: kauriorg/parity-docker
    ports:
      - "8545:8545"
    volumes:
      - .ethereum_data:/root/.local/share/io.parity.ethereum
      - .ethereum_log:/data/parity-logs
    environment:
      TRANSFER_AMOUNT: 10
      TRANSFER_ACCOUNTS: 0x627306090abaB3A6e1400e9345bC60c78a8BEf57,0xF0f15Cedc719B5A55470877B0710d5c7816916b1
    networks:
      - default

  truffle:
    image: gjeanmart/truffle-docker
    volumes:
      - ../contracts:/project
    ports:
      - "8888:8888"
    depends_on:
      - eth-node
    environment:
      NETWORK: docker
      API_PORT: 8888
      API_HOST: 0.0.0.0
    networks:
      - default

networks:
  default:
